//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace firstwebapp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public int id { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public Nullable<int> Age { get; set; }
        public int DeptID { get; set; }
        public string Email { get; set; }
        public string Image { get; set; }
        public string SocialNumber { get; set; }
        public string Teacher { get; set; }
    
        public virtual Department Department { get; set; }
    }
}
